services:
  mongo:
    image: mongo:7
    container_name: mongo_cv
    restart: always
    volumes:
      - gym_management_cv:/data/db
    networks:
      - cv_network 

  web:
    image: vishu7020/gym-django:cv
    container_name: django_cv
    restart: always
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    env_file:
      - /var/www/gym-django/.env.cv
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media      
    networks:
      - cv_network

volumes:
  gym_management_cv:
  static_volume:
  media_volume:

networks:
  cv_network:
    driver: bridge