services:
  mongo:
    image: mongo:7
    container_name: mongo_cv
    restart: always
    volumes:
      - gym_management_cv:/data/db
    networks:
      - cv_network 

  web:
    image: vishu7020/gym-django:cv
    container_name: django_cv
    restart: always
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - cv_network

volumes:
  gym_management_cv:

networks:
  cv_network:
    driver: bridge
