name: Build & Deploy Django App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set IMAGE TAG
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
        fi

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t vishu7020/gym-django:${IMAGE_TAG} .
        docker tag vishu7020/gym-django:${IMAGE_TAG} vishu7020/gym-django:stable

    - name: Push Docker image
      run: |
        docker push vishu7020/gym-django:${IMAGE_TAG}
        docker push vishu7020/gym-django:stable

    - name: Deploy to server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker rm -f django_app || true
          docker pull vishu7020/gym-django:stable
          docker run -d --name django_app \
            --restart always \
            --network host \
            --env-file /var/www/gym-django/.env \
            vishu7020/gym-django:stable
